In [1]:
import pandas as pd

In [2]:
pokemon = pd.read_csv('modified.csv')

In [3]:
df = pd.DataFrame(pokemon)

In [4]:
df.describe()

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Strength
count,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000,751.000000
mean,369.723036,423.322237,68.669774,75.978695,71.744341,70.213049,70.109188,66.607190,3.380826,146.191744
std,209.480412,112.932936,25.946152,29.920554,29.629870,30.263860,27.401096,27.845601,1.671360,49.947871
min,1.000000,180.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.000000,20.000000
25%,189.500000,325.000000,50.000000,55.000000,50.000000,45.000000,50.000000,45.000000,2.000000,110.000000
50%,377.000000,430.000000,65.000000,75.000000,68.000000,65.000000,65.000000,65.000000,3.000000,145.000000
75%,550.500000,500.000000,80.000000,95.000000,90.000000,90.000000,85.000000,88.500000,5.000000,178.500000
max,721.000000,770.000000,255.000000,180.000000,230.000000,180.000000,230.000000,180.000000,6.000000,360.000000

In [5]:
df['Type 2'].count()

375

In [9]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Strength
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False,114
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False,142
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False,182
3,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False,112
4,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False,144

In [ ]:
#Strongest Fire vs Water, who will win? (Felicia)
#Now one would naturally assume because of elemental advantage, Water would win, but let us see.
#I shall now just take 'Total' stat as an indicator of Strength/Who will win

In [30]:
df = df.drop('Strength', axis = 1)

In [ ]:
#before comparing individiuals, let's just look at Water vs Fire on a macro level

In [38]:
df.groupby(['Type 1']).sum().sort_values('Total', ascending = False)
#but sum doesn't really reveal much as we could simply have more Water than Fire pokeman.

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Water,33148,45156,7632,7682,7581,7839,7398,7024,311,4.0
Normal,30187,37071,7217,6799,5465,5141,5843,6606,288,2.0
Grass,23270,27106,4389,4701,4553,4943,4520,4000,225,3.0
Bug,22512,23851,3645,4257,4465,3532,4096,3856,216,0.0
Psychic,20584,23743,3623,3433,3463,4856,4353,4015,183,12.0
Fire,16433,21362,3329,3894,3155,4063,3370,3551,159,5.0
Electric,15503,18325,2471,2870,2732,3661,3053,3538,139,4.0
Rock,16171,17950,2646,3627,4090,2462,2996,2129,143,3.0
Ground,11401,14000,2361,3064,2715,1807,2008,2045,101,4.0
Dragon,12883,13447,2123,2753,2089,2269,2183,2030,105,9.0
Ghost,15120,12911,1938,2131,2443,2276,2269,1854,130,2.0
Dark,13412,12173,1881,2415,1902,1974,1890,2111,117,2.0
Poison,7050,11176,1883,2091,1927,1692,1803,1780,71,0.0
Steel,10764,10748,1486,1988,2677,1548,1797,1252,93,4.0
Fighting,9068,10109,1756,2368,1607,1214,1592,1572,84,0.0
Ice,9803,9823,1648,1626,1634,1741,1751,1423,82,2.0
Fairy,7642,7024,1260,1046,1117,1335,1440,826,70,1.0
Flying,2711,1940,283,315,265,377,290,410,22,2.0

In [59]:
water = df['Type 1'] == 'Water'
df[water].count()

#             107
Name          107
Type 1        107
Type 2         49
Total         107
HP            107
Attack        107
Defense       107
Sp. Atk       107
Sp. Def       107
Speed         107
Generation    107
Legendary     107
dtype: int64

In [62]:
fire = df['Type 1'] == 'Fire'
df[fire].count()

#             48
Name          48
Type 1        48
Type 2        20
Total         48
HP            48
Attack        48
Defense       48
Sp. Atk       48
Sp. Def       48
Speed         48
Generation    48
Legendary     48
dtype: int64

In [40]:
atype = df.groupby(['Type 1']).mean().sort_values('Total', ascending = False)
atype

,#,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Type 1,,,,,,,,,,
Dragon,495.500000,517.192308,81.653846,105.884615,80.346154,87.269231,83.961538,78.076923,4.038462,0.346154
Flying,677.750000,485.000000,70.750000,78.750000,66.250000,94.250000,72.500000,102.500000,5.500000,0.500000
Steel,468.000000,467.304348,64.608696,86.434783,116.391304,67.304348,78.130435,54.434783,4.043478,0.173913
Psychic,395.846154,456.596154,69.673077,66.019231,66.596154,93.384615,83.711538,77.211538,3.519231,0.230769
Fire,342.354167,445.041667,69.354167,81.125000,65.729167,84.645833,70.208333,73.979167,3.312500,0.104167
Rock,394.414634,437.804878,64.536585,88.463415,99.756098,60.048780,73.073171,51.926829,3.487805,0.073171
Ground,356.281250,437.500000,73.781250,95.750000,84.843750,56.468750,62.750000,63.906250,3.156250,0.125000
Electric,369.119048,436.309524,58.833333,68.333333,65.047619,87.166667,72.690476,84.238095,3.309524,0.095238
Dark,479.000000,434.750000,67.178571,86.250000,67.928571,70.500000,67.500000,75.392857,4.178571,0.071429
Ghost,504.000000,430.366667,64.600000,71.033333,81.433333,75.866667,75.633333,61.800000,4.333333,0.066667
Ice,426.217391,427.086957,71.652174,70.695652,71.043478,75.695652,76.130435,61.869565,3.565217,0.086957
Water,309.794393,422.018692,71.327103,71.794393,70.850467,73.261682,69.140187,65.644860,2.906542,0.037383
Fairy,449.529412,413.176471,74.117647,61.529412,65.705882,78.529412,84.705882,48.588235,4.117647,0.058824
Grass,352.575758,410.696970,66.500000,71.227273,68.984848,74.893939,68.484848,60.606061,3.409091,0.045455
Fighting,362.720000,404.360000,70.240000,94.720000,64.280000,48.560000,63.680000,62.880000,3.360000,0.000000
Poison,251.785714,399.142857,67.250000,74.678571,68.821429,60.428571,64.392857,63.571429,2.535714,0.000000
Normal,321.138298,394.372340,76.776596,72.329787,58.138298,54.691489,62.159574,70.276596,3.063830,0.021277
Bug,346.338462,366.938462,56.076923,65.492308,68.692308,54.338462,63.015385,59.323077,3.323077,0.000000

In [47]:
#how much stronger are Fire types over Water?
atype.loc['Fire','Total'] - atype.loc['Water','Total']

23.022975077881654

In [ ]:
#instead of filtering a Fire DF and a Water type DF, I shall attempt to just compare and locate the pokemon in one block

In [84]:
filter = (df['Type 1'] == 'Water') | (df['Type 1'] == 'Fire')

In [85]:
df[filter]
#so I clearly fucked up something here, all Type 1 have been replcaed with water. so, time to restart

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Water,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Water,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Water,Poison,525,80,82,83,100,100,80,1,False
3,4,Charmander,Water,NaN,309,39,52,43,60,50,65,1,False
4,5,Charmeleon,Water,NaN,405,58,64,58,80,65,80,1,False
5,6,Charizard,Water,Flying,534,78,84,78,109,85,100,1,False
6,7,Squirtle,Water,NaN,314,44,48,65,50,64,43,1,False
7,8,Wartortle,Water,NaN,405,59,63,80,65,80,58,1,False
8,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
9,10,Caterpie,Water,NaN,195,45,30,35,20,20,45,1,False
10,11,Metapod,Water,NaN,205,50,20,55,25,25,30,1,False
11,12,Butterfree,Water,Flying,395,60,45,50,90,80,70,1,False
12,13,Weedle,Water,Poison,195,40,35,30,20,20,50,1,False
13,14,Kakuna,Water,Poison,205,45,25,50,25,25,35,1,False
14,15,Beedrill,Water,Poison,395,65,90,40,45,80,75,1,False
15,16,Pidgey,Water,Flying,251,40,45,40,35,35,56,1,False
16,17,Pidgeotto,Water,Flying,349,63,60,55,50,50,71,1,False
17,18,Pidgeot,Water,Flying,479,83,80,75,70,70,101,1,False
18,19,Rattata,Water,NaN,253,30,56,35,25,35,72,1,False
19,20,Raticate,Water,NaN,413,55,81,60,50,70,97,1,False
20,21,Spearow,Water,Flying,262,40,60,30,31,31,70,1,False
21,22,Fearow,Water,Flying,442,65,90,65,61,61,100,1,False
22,23,Ekans,Water,NaN,288,35,60,44,40,54,55,1,False
23,24,Arbok,Water,NaN,438,60,85,69,65,79,80,1,False
24,25,Pikachu,Water,NaN,320,35,55,40,50,50,90,1,False
25,26,Raichu,Water,NaN,485,60,90,55,90,80,110,1,False
26,27,Sandshrew,Water,NaN,300,50,75,85,20,30,40,1,False
27,28,Sandslash,Water,NaN,450,75,100,110,45,55,65,1,False
28,29,Nidoran (Female),Water,NaN,275,55,47,52,40,40,41,1,False
29,30,Nidorina,Water,NaN,365,70,62,67,55,55,56,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
721,699,Aurorus,Water,Ice,521,123,77,72,99,92,58,6,False
722,700,Sylveon,Water,NaN,525,95,65,65,110,130,60,6,False
723,701,Hawlucha,Water,Flying,500,78,92,75,74,63,118,6,False
724,702,Dedenne,Water,Fairy,431,67,58,57,81,67,101,6,False
725,703,Carbink,Water,Fairy,500,50,50,150,50,150,50,6,False
726,704,Goomy,Water,NaN,300,45,50,35,55,75,40,6,False
727,705,Sliggoo,Water,NaN,452,68,75,53,83,113,60,6,False
728,706,Goodra,Water,NaN,600,90,100,70,110,150,80,6,False
729,707,Klefki,Water,Fairy,470,57,80,91,80,87,75,6,False
730,708,Phantump,Water,Grass,309,43,70,48,50,60,38,6,False
731,709,Trevenant,Water,Grass,474,85,110,76,65,82,56,6,False
732,710,PumpkabooAverage Size,Water,Grass,335,49,66,70,44,55,51,6,False
733,710,PumpkabooSmall Size,Water,Grass,335,44,66,70,44,55,56,6,False
734,710,PumpkabooLarge Size,Water,Grass,335,54,66,70,44,55,46,6,False
735,710,PumpkabooSuper Size,Water,Grass,335,59,66,70,44,55,41,6,False
736,711,GourgeistAverage Size,Water,Grass,494,65,90,122,58,75,84,6,False
737,711,GourgeistSmall Size,Water,Grass,494,55,85,122,58,75,99,6,False
738,711,GourgeistLarge Size,Water,Grass,494,75,95,122,58,75,69,6,False
739,711,GourgeistSuper Size,Water,Grass,494,85,100,122,58,75,54,6,False
740,712,Bergmite,Water,NaN,304,55,69,85,32,35,28,6,False
741,713,Avalugg,Water,NaN,514,95,117,184,44,46,28,6,False
742,714,Noibat,Water,Dragon,245,40,30,35,45,40,55,6,False
743,715,Noivern,Water,Dragon,535,85,70,80,97,80,123,6,False
744,716,Xerneas,Water,NaN,680,126,131,95,131,98,99,6,True
745,717,Yveltal,Water,Flying,680,126,131,95,131,98,99,6,True
746,718,Zygarde50% Forme,Water,Ground,600,108,100,121,81,95,95,6,True
747,719,Diancie,Water,Fairy,600,50,100,150,100,150,50,6,True
748,720,HoopaHoopa Confined,Water,Ghost,600,80,110,60,150,130,70,6,True
749,720,HoopaHoopa Unbound,Water,Dark,680,80,160,60,170,130,80,6,True
750,721,Volcanion,Water,Water,600,80,110,120,130,90,70,6,True

In [81]:
list = []
for row in df:
    if 'Type 1 ' == 'Water':
        list.append(row)
    elif 'Type 1' == 'Fire':
        list.append(row)

In [82]:
list

[]